#!/bin/bash

buildsimh() {
  git clone https://github.com/simh/simh.git
  cd simh
  #git checkout $1
  gmake vax || make vax
  strip BIN/microvax3900
  cd ..
}

buildgzcompat() {
  (
    echo '#include <stdlib.h>'
    tar -xOf compress/compress.tar ucb/compress/gzcompat.c
  )>gzcompat.c

  gcc -Wno-implicit-int -O -o gzcompat gzcompat.c || cc -Wno-implicit-int -O -o gzcompat gzcompat.c
}

buildgzcompatwin() {
tar -xOf compress/compress.tar ucb/compress/gzcompat.c >gzcompat.c
patch gzcompat.c <<__EOF__
7a8,12
> #include <stdlib.h>
> #ifdef _WIN32
>   #include <io.h>
>   #include <fcntl.h>
> #endif
31a37
>         int argc;
39c45,48
<$(printf ' ')
---
> #ifdef _WIN32
>         setmode(fileno(stdout),O_BINARY);
>         setmode(fileno(stdin),O_BINARY);
> #endif
__EOF__
gcc -O -o gzcompat gzcompat.c
}

maketap() {
  cat 4.3BSD-Quasijarus0c/miniroot.Z   | ./gzcompat | gzip -dc > miniroot
  cat 4.3BSD-Quasijarus0c/rootdump.Z   | ./gzcompat | gzip -dc > rootdump
  cat 4.3BSD-Quasijarus0c/src.tar.Z    | ./gzcompat | gzip -dc > src.tar
  cat 4.3BSD-Quasijarus0c/srcsys.tar.Z | ./gzcompat | gzip -dc > srcsys.tar
  cat 4.3BSD-Quasijarus0c/stand.Z      | ./gzcompat | gzip -dc > stand
  cat 4.3BSD-Quasijarus0c/usr.tar.Z    | ./gzcompat | gzip -dc > usr.tar
  perl mkdisttap/mkdisttap.pl > quas.tap
  cksum miniroot rootdump src.tar srcsys.tar stand usr.tar quas.tap
}

writeinis() {
cat >config.ini <<__EOF__
SET CPU 32M
SET CPU NOIDLE
SET CONSOLE SPEED=1200
#SET CPU IDLE=QUASIJARUS
set cr  dis
set lpt dis
set rl  dis
set ts  dis
set xq  dis
set rq0 ra82,NOAUTOSIZE,FORMAT=VHD
set rq1 ra82,NOAUTOSIZE,FORMAT=VHD
set rq2 ra82,NOAUTOSIZE,FORMAT=VHD
att rq0 quas.dsk
att rq1 extra.dsk
att rq2 local.dsk
set rq3 dis
att tq0 quas.tap
set tti 7b
set tto 7b
set dz lines=16
set runlimit 14 minutes
set console telnet=65432
SET CONSOLE TELNET=LOG=log_file
set console telnet=buffered=1000000
__EOF__

cat >rootdump.ini <<__EOF__
DO config.ini
EXPECT ">>>"               SEND "boot mua0:\r"                          ;GO
EXPECT "\r\n\n="           SEND "copy\r"                                ;GO
EXPECT "From: "            SEND "tms(0,1)\r"                            ;GO
EXPECT "To: "              SEND "ra(0,1)\r"                             ;GO
EXPECT "copied\n\r="       SEND "boot\r"                                ;GO
EXPECT "Boot\n\r: "        SEND "ra(0,1)vmunix\r"                       ;GO
EXPECT "root device? "     SEND "ra0*\r"                                ;GO
EXPECT "intr ^C\r\n# "     SEND \
"disklabel -rw ra0 ra82 \x22Quasijarus\x22 \
/usr/mdec/rdboot /usr/mdec/bootra\x3B cd /dev\x3B MAKEDEV ra1 2>/dev/null \x3Bcd /\x3Bdisklabel -rw ra1 ra82 \x222\x22 /usr/mdec/rdboot /usr/mdec/bootra\r" ;GO
EXPECT "bootra\r\n# "      SEND "disk=ra0 type=ra82 tape=tms xtr\r"     ;GO
EXPECT "cassette\r\n# "    SEND "sync\x3B sync\x3B sync\r"              ;GO
EXPECT "sync\r\n# "       ;QUIT
BOOT CPU
__EOF__

cat >install.ini <<"__EOF__"
DO config.ini
ATT NVR nvram.dat
DEP BDR 1
EXPECT "Device\? \x5BXQA0\x5D: " SEND "dua0:\r" ;GO
EXPECT "intr ^C\r\n# "           SEND "cd /dev\x3B MAKEDEV ra1 \x3Bnewfs ra1g ra82\x3B newfs ra0h ra82\r" ;GO
EXPECT ",\r\n# "                 SEND "mkdir /home\x3B mount /dev/ra1g /usr\r" ;GO
EXPECT "usr\r\n# "               SEND "cd /dev\x3B MAKEDEV tmscp0\x3B MAKEDEV dz0\r" ;GO
EXPECT "dz0\r\n# "               SEND "mount /dev/ra1a /usr \x3B cd /usr\x3B mt rew\x3B mt fsf 3\x3B tar xvpbf 20 /dev/rmt12|sed '$!d'\r" ;GO
EXPECT "0b, 5120 bytes, 10 tape blocks\r\n# " SEND "mkdir src\x3B cd src\x3B mkdir sys\x3B cd sys\x3B mt fsf  \x3B tar xvpbf 20 /dev/rmt12|tail\r" ;GO
EXPECT "link to ../mdec/boot58/bootblk\r\n# " SEND "cd ..\x3B mt fsf  \x3B tar xvpbf 20 /dev/rmt12|tail\r" ;GO
EXPECT "ey.c, 712 bytes, 2 tape blocks\r\n# " SEND "echo '1d|w|q|' |tr '|' '\x5C012' | ed /usr/lib/crontab\x3B echo \x22/dev/ra0a:/:rw:1:1|/dev/ra0h:/home:rw:1:3|/dev/ra1g:/usr:rw:1:2\x22 |tr '|' '\x5C012' >/etc/fstab\x3B shutdown -h now\r"; GO
BOOT CPU
QUIT
__EOF__

cat >movestuff.ini <<"__EOF__"
DO config.ini
ATT NVR nvram.dat
DEP BDR 1
EXPECT "login: "              SEND "root\r"; GO
EXPECT "intr ^C\r\n# "        SEND "cd /dev\x3B MAKEDEV ra2\x3Bdisklabel -rw ra2 ra82 \x2232\x22 /usr/mdec/rdboot /usr/mdec/bootra\r"; GO
EXPECT "bootra\r\n# "         SEND "newfs ra2a ra82\x3B newfs ra2b ra82\x3B newfs ra2h ra82\x3B newfs ra2g ra82\x3B newfs ra0g ra82\r"; GO
EXPECT ",\r\n# "              SEND "mkdir /mnt/a /mnt/b /mnt/h /mnt/g /mnt/g2\x3B mount /dev/ra2h /mnt/h\x3B rm /sys\x3B mkdir /sys\x3B cd /usr/src/sys\x3B find . -print | cpio -pdum /mnt/h\x3B cd ..\x3B rm -rf sys\x3B ln -s /sys sys\x3B echo done sys\r"; GO
EXPECT "done sys\r\n# "       SEND "mount /dev/ra2g /mnt/g\x3B cd /usr/spool\x3B find . -print | cpio -pdum /mnt/g\x3B rm -rf *\x3B echo done spool\r"; GO
EXPECT "done spool\r\n# "     SEND "mount /dev/ra2b /mnt/b\x3B cd /usr/local\x3B find . -print | cpio -pdum /mnt/b\x3B rm -rf *\x3B echo done local\r"; GO
EXPECT "done local\r\n# "     SEND "mkdir /mnt/b/adm\x3B cd /usr/adm\x3B find . -print | cpio -pdum /mnt/b/adm\x3B cd ..\x3B rm -rf adm\x3B ln -s /usr/local/adm adm\x3B echo done adm\r"; GO
EXPECT "done adm\r\n# "       SEND "mount /dev/ra0g /mnt/g2\x3B cd /usr/lib\x3B find . -print | cpio -pdum /mnt/g2\x3B rm -rf *\x3B >/etc/mtab\x3B echo done lib\r"; GO
EXPECT "done lib\r\n# "       SEND "sed -e 's/rw:1:2/ro:0:0/' /etc/fstab >/f\x3B echo \x22/dev/ra2a:/tmp:rw:1:2|/dev/ra2b:/usr/local:rw:1:2|/dev/ra2h:/sys:rw:1:2|/dev/ra2g:/usr/spool:rw:1:2|/dev/ra0g:/usr/lib:rw:1:2|\x22 | tr '|' '\x5C012' >>/f\x3B mv /f /etc/fstab\r"; GO
EXPECT "fstab\r\n# "          SEND "rm /restoresymtable\x3B sync\x3B sync\x3B sync\x3B shutdown -h now\r"; GO
BOOT CPU
QUIT
__EOF__

cat >sv.ini<<__EOF__
SHOW VERSION
DO config.ini
SHOW CONSOLE
SHOW DEV
SHOW CLOCKS
QUIT
__EOF__

runit() {
  simh/BIN/microvax3900 sv.ini
  rm nvram.dat
  rm all_log_file 2>/dev/null
  rm quas.dsk extra.dsk local.dsk 2>/dev/null
  date
  simh/BIN/microvax3900 rootdump.ini
  date
  cat log_file >all_log_file; rm log_file
  rm nvram.dat
  date
  simh/BIN/microvax3900 install.ini
  date
  cat log_file |tee -a all_log_file
  simh/BIN/microvax3900 movestuff.ini
  cat log_file |tee -a all_log_file
  rm log_file
  cat config.ini |egrep -vi "CONSOLE|runlimit" | sed -e's/#SET CPU IDLE=QUASIJARUS/SET CPU IDLE=QUASIJARUS/' >run.ini
  printf "ATT NVR nvram.dat\nDEP BDR 1\nBOOT CPU\n" >>run.ini
}

main() {
  buildsimh $1
  buildgzcompat
  maketap
  writeinis
  runit
}

echo starting

((${#}-2))&&$1
((${#}-1))&&main $2
